import markdown
import requests
from io import BytesIO
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from htmldocx import HtmlToDocx
from xhtml2pdf import pisa
import base64
import re

# Логотип
FORTE_LOGO_URL = "https://upload.wikimedia.org/wikipedia/commons/e/e3/Fortebank_Logo.png"


def markdown_to_styled_html(markdown_text, font_name="sans-serif"):
    html_body = markdown.markdown(markdown_text, extensions=['tables'])

    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            @page {{
                size: A4;
                margin: 2cm;
            }}

            body {{
                font-family: '{font_name}', sans-serif;
                font-size: 11pt;
                line-height: 1.5;
                color: #333333;
            }}

            /* Forte Branding Colors */
            h1 {{
                color: #9F2349; /* Бордовый */
                font-size: 24pt;
                border-bottom: 2px solid #9F2349;
                padding-bottom: 10px;
                margin-top: 0;
            }}

            h2 {{
                color: #2D2D2D; /* Темно-серый */
                font-size: 18pt;
                margin-top: 20px;
                margin-bottom: 10px;
            }}

            h3 {{
                color: #9F2349;
                font-size: 14pt;
                margin-top: 15px;
            }}

            /* Таблицы */
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 15px;
                margin-bottom: 15px;
            }}

            th, td {{
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
            }}

            th {{
                background-color: #f2f2f2;
                color: #9F2349;
                font-weight: bold;
            }}

            /* Списки */
            ul, ol {{
                margin-top: 5px;
                margin-bottom: 5px;
            }}

            /* Водяной знак (только для PDF через CSS) */
            .watermark {{
                color: #eeeeee;
                font-size: 60pt;
                transform: rotate(-45deg);
                position: fixed;
                top: 40%;
                left: 20%;
                z-index: -1;
            }}

            .header-logo {{
                color: #9F2349;
                font-size: 10pt;
                text-align: right;
                margin-bottom: 30px;
                font-weight: bold;
            }}
        </style>
    </head>
    <body>
        <div class="header-logo">GENERATED BY FORTE AI ANALYST</div>
        <!-- Тело документа -->
        {html_body}
    </body>
    </html>
    """
    return html_template


def create_chat_pdf(messages):
    font_name = 'Arial'

    chat_body = "<h1>Протокол интервью (Chat Log)</h1>"

    for msg in messages:
        role = "Клиент" if msg['role'] == 'user' else "Forte AI"
        color = "#333" if msg['role'] == 'user' else "#9F2349"
        bg = "#f9f9f9" if msg['role'] == 'user' else "#fff5f7"

        text_content = markdown.markdown(msg['content'])

        chat_body += f"""
        <div style="background-color: {bg}; border-left: 4px solid {color}; padding: 10px; margin-bottom: 15px;">
            <div style="font-weight: bold; color: {color}; margin-bottom: 5px;">{role}</div>
            <div style="font-size: 10pt;">{text_content}</div>
        </div>
        """

    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            @page {{ size: A4; margin: 2cm; }}
            body {{ font-family: '{font_name}', sans-serif; font-size: 11pt; }}
            h1 {{ color: #9F2349; border-bottom: 2px solid #9F2349; }}
        </style>
    </head>
    <body>
        {chat_body}
    </body>
    </html>
    """

    buffer = BytesIO()
    pisa.CreatePDF(src=full_html, dest=buffer, encoding='UTF-8')
    buffer.seek(0)
    return buffer


def get_mermaid_image(mermaid_code):
    try:
        full_code = mermaid_code

        graphbytes = full_code.encode("utf8")
        base64_bytes = base64.b64encode(graphbytes)
        base64_string = base64_bytes.decode("ascii")

        url = "https://mermaid.ink/img/" + base64_string

        response = requests.get(url)
        if response.status_code == 200:
            return BytesIO(response.content)
    except Exception as e:
        print(f"Ошибка генерации Mermaid: {e}")
    return None


def create_docx(markdown_text):
    doc = Document()

    try:
        response = requests.get(FORTE_LOGO_URL)
        if response.status_code == 200:
            doc.add_picture(BytesIO(response.content), width=Inches(2))
    except:
        pass

    title = doc.add_heading('Business Requirements Document', 0)
    title.runs[0].font.color.rgb = RGBColor(159, 35, 73)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph('Generated by Forte AI Analyst').alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_page_break()

    new_parser = HtmlToDocx()

    parts = re.split(r'(```mermaid[\s\S]*?```)', markdown_text)

    for part in parts:
        if not part.strip(): continue

        if part.strip().startswith("```mermaid"):
            code = part.replace("```mermaid", "").replace("```", "").strip()
            print("Generating Mermaid image for Word...")
            img_data = get_mermaid_image(code)

            if img_data:
                try:
                    doc.add_picture(img_data, width=Inches(6))
                    last_p = doc.paragraphs[-1]
                    last_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    doc.add_paragraph("")
                except Exception as e:
                    doc.add_paragraph(f"[Error inserting diagram image: {e}]")
            else:
                doc.add_paragraph("[Error: Could not generate diagram image]")
        else:
            raw_html = markdown.markdown(part, extensions=['tables'])
            new_parser.add_html_to_document(raw_html, doc)

    for paragraph in doc.paragraphs:
        if paragraph.style.name.startswith('Heading'):
            for run in paragraph.runs:
                run.font.name = 'Arial'
                run.font.color.rgb = RGBColor(159, 35, 73)

    for table in doc.tables:
        table.style = 'Table Grid'

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer